name: Hello actions
on: 
  push:
    branches: ["main"]
jobs:
   hello:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: step1
           run: echo Done step 1
         - name: step2
           run:  echo Done step 2
         - name: step3
           run: | 
              echo running multiline command
              echo finished job
